FROM ubuntu:20.04
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata -q  icinga2 icinga2-ido-pgsql
RUN apt-get install -y \
    mariadb-server \
    phpmyadmin \
    php-mbstring \
    php-xml \
    php-gd \
    php-curl \
    apache2
RUN service mariadb start
RUN mysql -u root -p"" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';"
RUN mysql -u root -p"" -e "FLUSH PRIVILEGES;"
# create config.inc.php
RUN echo "<?php" > /etc/phpmyadmin/config.inc.php
RUN echo "$cfg['Servers'][$i]['host'] = 'localhost';" >> /etc/phpmyadmin/config.inc.php
RUN echo "$cfg['Servers'][$i]['port'] = '3306';" >> /etc/phpmyadmin/config.inc.php
RUN echo "$cfg['Servers'][$i]['user'] = 'root';" >> /etc/phpmyadmin/config.inc.php
RUN echo "$cfg['Servers'][$i]['password'] = 'admin';" >> /etc/phpmyadmin/config.inc.php
RUN echo "?>" >> /etc/phpmyadmin/config.inc.php
# create .my.cnf
RUN echo "[client]" > /root/.my.cnf
RUN echo "user=root" >> /root/.my.cnf
RUN echo "password=admin" >> /root/.my.cnf
# create .bashrc
RUN echo "export MYSQL_PWD=root"
CMD ["service", "apache2", "start"]